export const PERMISSION_DEFINITIONS = Object.freeze([
  {
    key: "DASHBOARD_VIEW",
    code: "dashboard.view",
    nama: "Lihat Dashboard",
    modul: "dashboard",
    deskripsi: "Dapat melihat dashboard",
  },
  {
    key: "DASHBOARD_EXPORT",
    code: "dashboard.export",
    nama: "Export Dashboard",
    modul: "dashboard",
    deskripsi: "Dapat export data dari dashboard",
  },
  {
    key: "TRANSACTION_CREATE",
    code: "transaction.create",
    nama: "Buat Transaksi",
    modul: "transaction",
    deskripsi: "Dapat membuat transaksi baru",
  },
  {
    key: "TRANSACTION_READ",
    code: "transaction.read",
    nama: "Lihat Transaksi",
    modul: "transaction",
    deskripsi: "Dapat melihat transaksi",
  },
  {
    key: "TRANSACTION_UPDATE",
    code: "transaction.update",
    nama: "Update Transaksi",
    modul: "transaction",
    deskripsi: "Dapat mengupdate transaksi",
  },
  {
    key: "TRANSACTION_DELETE",
    code: "transaction.delete",
    nama: "Hapus Transaksi",
    modul: "transaction",
    deskripsi: "Dapat menghapus transaksi",
  },
  {
    key: "TRANSACTION_PRINT",
    code: "transaction.print",
    nama: "Cetak Transaksi",
    modul: "transaction",
    deskripsi: "Dapat mencetak struk transaksi",
  },
  {
    key: "PRODUCT_CREATE",
    code: "product.create",
    nama: "Buat Produk",
    modul: "product",
    deskripsi: "Dapat membuat produk baru",
  },
  {
    key: "PRODUCT_READ",
    code: "product.read",
    nama: "Lihat Produk",
    modul: "product",
    deskripsi: "Dapat melihat produk",
  },
  {
    key: "PRODUCT_UPDATE",
    code: "product.update",
    nama: "Update Produk",
    modul: "product",
    deskripsi: "Dapat mengupdate produk",
  },
  {
    key: "PRODUCT_DELETE",
    code: "product.delete",
    nama: "Hapus Produk",
    modul: "product",
    deskripsi: "Dapat menghapus produk",
  },
  {
    key: "STOCK_VIEW",
    code: "stock.view",
    nama: "Lihat Stok",
    modul: "stock",
    deskripsi: "Dapat melihat stok",
  },
  {
    key: "STOCK_ADJUST",
    code: "stock.adjust",
    nama: "Sesuaikan Stok",
    modul: "stock",
    deskripsi: "Dapat menyesuaikan stok",
  },
  {
    key: "STOCK_TRANSFER",
    code: "stock.transfer",
    nama: "Transfer Stok",
    modul: "stock",
    deskripsi: "Dapat transfer stok antar cabang",
  },
  {
    key: "REPORT_VIEW",
    code: "report.view",
    nama: "Lihat Laporan",
    modul: "report",
    deskripsi: "Dapat melihat laporan",
  },
  {
    key: "REPORT_EXPORT",
    code: "report.export",
    nama: "Export Laporan",
    modul: "report",
    deskripsi: "Dapat export laporan",
  },
  {
    key: "FORECAST_VIEW",
    code: "forecast.view",
    nama: "Lihat Forecast",
    modul: "forecast",
    deskripsi: "Dapat melihat forecast penjualan",
  },
  {
    key: "FORECAST_GENERATE",
    code: "forecast.generate",
    nama: "Generate Forecast",
    modul: "forecast",
    deskripsi: "Dapat generate forecast baru",
  },
  {
    key: "BI_VIEW",
    code: "bi.view",
    nama: "Lihat BI",
    modul: "bi",
    deskripsi: "Dapat melihat business intelligence",
  },
  {
    key: "BRANCH_VIEW",
    code: "branch.view",
    nama: "Lihat Cabang",
    modul: "branch",
    deskripsi: "Dapat melihat data cabang",
  },
  {
    key: "BRANCH_CREATE",
    code: "branch.create",
    nama: "Buat Cabang",
    modul: "branch",
    deskripsi: "Dapat membuat cabang baru",
  },
  {
    key: "BRANCH_UPDATE",
    code: "branch.update",
    nama: "Update Cabang",
    modul: "branch",
    deskripsi: "Dapat mengupdate cabang",
  },
  {
    key: "BRANCH_DELETE",
    code: "branch.delete",
    nama: "Hapus Cabang",
    modul: "branch",
    deskripsi: "Dapat menghapus cabang",
  },
  {
    key: "BRANCH_SWITCH",
    code: "branch.switch",
    nama: "Ganti Cabang",
    modul: "branch",
    deskripsi: "Dapat mengganti/memilih cabang lain",
  },
  {
    key: "BRANCH_GLOBAL",
    code: "branch.global",
    nama: "Akses Global Branch",
    modul: "branch",
    deskripsi: "Dapat mengakses semua cabang secara global",
  },
  {
    key: "ROLE_VIEW",
    code: "role.view",
    nama: "Lihat Role",
    modul: "role",
    deskripsi: "Dapat melihat role",
  },
  {
    key: "ROLE_CREATE",
    code: "role.create",
    nama: "Buat Role",
    modul: "role",
    deskripsi: "Dapat membuat role baru",
  },
  {
    key: "ROLE_UPDATE",
    code: "role.update",
    nama: "Update Role",
    modul: "role",
    deskripsi: "Dapat mengupdate role",
  },
  {
    key: "ROLE_DELETE",
    code: "role.delete",
    nama: "Hapus Role",
    modul: "role",
    deskripsi: "Dapat menghapus role",
  },
  {
    key: "PERMISSION_VIEW",
    code: "permission.view",
    nama: "Lihat Permission",
    modul: "permission",
    deskripsi: "Dapat melihat permission",
  },
  {
    key: "PERMISSION_MANAGE",
    code: "permission.manage",
    nama: "Kelola Permission",
    modul: "permission",
    deskripsi: "Dapat mengelola permission",
  },
  {
    key: "USER_VIEW",
    code: "user.view",
    nama: "Lihat User",
    modul: "user",
    deskripsi: "Dapat melihat user",
  },
  {
    key: "USER_CREATE",
    code: "user.create",
    nama: "Buat User",
    modul: "user",
    deskripsi: "Dapat membuat user baru",
  },
  {
    key: "USER_UPDATE",
    code: "user.update",
    nama: "Update User",
    modul: "user",
    deskripsi: "Dapat mengupdate user",
  },
  {
    key: "USER_DELETE",
    code: "user.delete",
    nama: "Hapus User",
    modul: "user",
    deskripsi: "Dapat menghapus user",
  },
  {
    key: "EMPLOYEE_MANAGE",
    code: "employee.manage",
    nama: "Kelola Karyawan",
    modul: "employee",
    deskripsi: "Dapat mengelola karyawan",
  },
  {
    key: "SECURITY_VIEW",
    code: "security.view",
    nama: "Lihat Security",
    modul: "security",
    deskripsi: "Dapat melihat log keamanan",
  },
  {
    key: "SECURITY_MANAGE",
    code: "security.manage",
    nama: "Kelola Security",
    modul: "security",
    deskripsi: "Dapat mengelola keamanan",
  },
]);

export const PERMISSIONS = Object.freeze(
  Object.fromEntries(PERMISSION_DEFINITIONS.map((permission) => [permission.key, permission.code]))
);

export const PERMISSION_CODES = PERMISSIONS;

export const PERMISSION_LIST = Object.freeze(PERMISSION_DEFINITIONS.map((permission) => permission.code));

export const getPermissionCode = (key) => PERMISSIONS[key];
